packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1107.0'
overrides:
  browserslist: 4.24.3
  nanoid: ^3.3.17
  esbuild: ^0.25.0
